version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    command: tail -f /dev/null
    volumes:
      - ./server:/app
    ports:
      - 8081:8080
    stdin_open: true
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    command: tail -f /dev/null
    volumes:
      - ./worker:/app
    ports:
      - 8082:8080
    stdin_open: true
