version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    command: ruby webrick.rb
    volumes:
      - ./server:/app
    ports:
      - 8082:8082
    stdin_open: true
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    command: tail -f /dev/null
    volumes:
      - ./worker:/app
    stdin_open: true
  go:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run server1.go
    volumes:
      - ./go:/app
    ports:
      - 8083:8083
    stdin_open: true
